### ISSUE TITLE
Problems with wc:query-runtimes

### ISSUE THREAD

**Issue by Rubenito** [stratosphere/peel#54]
When I try to use the wc:query-runtimes function peel provides, after initializing and updating it with the data like mentioned here: http://peel-framework.org/getting-started.html
I get the following error, which basicly states, that the function "MEDIAN" is not supported:

Unexpected error: Function "MEDIAN" not found; SQL statement:
SELECT   e.suite         as suite,
         e.name          as name,
         MEDIAN(er.time) as median_time,
         MIN(er.time) as min_time,
         MAX(er.time) as max_time
FROM     experiment      e,
         experiment_run  er
WHERE    e.id = er.experiment_id
AND      e.suite = ?
GROUP BY e.suite, e.name
ORDER BY e.suite, e.name [90022-187]
org.h2.jdbc.JdbcSQLException: Function "MEDIAN" not found; SQL statement:
SELECT   e.suite         as suite,
         e.name          as name,
         MEDIAN(er.time) as median_time,
         MIN(er.time) as min_time,
         MAX(er.time) as max_time
FROM     experiment      e,
         experiment_run  er
WHERE    e.id = er.experiment_id
AND      e.suite = ?
GROUP BY e.suite, e.name
ORDER BY e.suite, e.name [90022-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readJavaFunction(Parser.java:2351)
	at org.h2.command.Parser.readFunction(Parser.java:2403)
	at org.h2.command.Parser.readTerm(Parser.java:2737)
	at org.h2.command.Parser.readFactor(Parser.java:2259)
	at org.h2.command.Parser.readSum(Parser.java:2246)
	at org.h2.command.Parser.readConcat(Parser.java:2216)
	at org.h2.command.Parser.readCondition(Parser.java:2066)
	at org.h2.command.Parser.readAnd(Parser.java:2038)
	at org.h2.command.Parser.readExpression(Parser.java:2030)
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:1942)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1974)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1868)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1689)
	at org.h2.command.Parser.parseSelect(Parser.java:1677)
	at org.h2.command.Parser.parsePrepared(Parser.java:433)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:277)
	at anorm.SimpleSql.getFilledStatement(SimpleSql.scala:59)
	at anorm.SimpleSql$$anonfun$preparedStatement$1.apply(SimpleSql.scala:70)
	at anorm.SimpleSql$$anonfun$preparedStatement$1.apply(SimpleSql.scala:70)
	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:106)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:85)
	at resource.ManagedResourceOperations$$anon$2.acquireFor(ManagedResourceOperations.scala:40)
	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:27)
	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.DeferredExtractableManagedResource.acquireAndGet(AbstractManagedResource.scala:24)
	at anorm.Sql$$anonfun$asTry$1.apply(Anorm.scala:302)
	at anorm.Sql$$anonfun$asTry$1.apply(Anorm.scala:302)
	at scala.util.Try$.apply(Try.scala:161)
	at anorm.Sql$.asTry(Anorm.scala:302)
	at anorm.WithResult$class.as(SqlResult.scala:120)
	at anorm.SimpleSql.as(SimpleSql.scala:6)
	at de.tuberlin.cit.experiments.iterations.cli.command.QueryRuntimes.run(QueryRuntimes.scala:87)
	at org.peelframework.core.cli.Peel$.main(Peel.scala:104)
	at org.peelframework.core.cli.Peel.main(Peel.scala)

**Comment by aalexandrov** [comment]
I thin that the version of the [QueryRuntimes](https://github.com/stratosphere/peel-wordcount/blob/master/peel-wordcount-peelextensions/src/main/scala/org/peelframework/wordcount/cli/command/QueryRuntimes.scala) file that you are using is not up to date. Can you diff against the one in the `peel-wordcount` repository?

**Comment by Rubenito** [comment]
Das war das Problem, nachdem ich QueryRuntimes ausgetauscht habe funktioniert alles. 

Vielen Dank!
