### ISSUE TITLE
wordcount.default suite fails on second attempt

### ISSUE THREAD

**Issue by joh-mue** [stratosphere/peel#62]
Following the instruction on the getting started page I could get peel to work and run the wordcount.default suite once (except for the spark part that will fail as mentioned in #61) but when I try it a second time the following error is thrown:

```
...
15-11-11 15:29:48 [INFO] +-- Loading experiment configuration
15-11-11 15:29:48 [INFO] +-- Loading current runtime values as configuration
15-11-11 15:29:48 [INFO] +-- Loading system properties as configuration
15-11-11 15:29:48 [INFO] `-- Resolving configuration
15-11-11 15:29:48 [INFO] Executing experiments in suite
15-11-11 15:29:48 [INFO] ############################################################
15-11-11 15:29:48 [INFO] Tearing down systems with SUITE lifespan
Unexpected error: No configuration setting found for key 'system'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'system'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at org.peelframework.hadoop.beans.system.HDFS2.isRunning(HDFS2.scala:132)
	at org.peelframework.core.beans.system.System.tearDown(System.scala:84)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$3.apply(Run.scala:187)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$3.apply(Run.scala:186)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.peelframework.core.cli.command.suite.Run.run(Run.scala:186)
	at org.peelframework.core.cli.Peel$.main(Peel.scala:104)
	at org.peelframework.core.cli.Peel.main(Peel.scala)
```

The issue is reproducible and has been confirmed on a mac and linux machine.

**Comment by aalexandrov** [comment]
Fixed in 2c844f26cabb6ebbaea7091b2c4804aafe8025e1. Thanks for reporting the bug.
